# Generated by Django 2.2.2 on 2019-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_client',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='app'),
        ),
    ]
