# Generated by Django 2.2.2 on 2019-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0002_registration_client_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='app')),
            ],
        ),
    ]
