# Generated by Django 2.2.2 on 2019-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration_developer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='app'),
        ),
    ]
