# Generated by Django 2.2.2 on 2019-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0004_registration_developer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(upload_to='developerdp'),
        ),
        migrations.AlterField(
            model_name='registration_client',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='clientdp'),
        ),
    ]
