# Generated by Django 2.2.2 on 2019-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0005_auto_20190804_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_developer',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='developerdp'),
        ),
    ]
