# Generated by Django 2.2.2 on 2019-08-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0006_auto_20190804_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='importcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(upload_to='importcsv')),
            ],
        ),
    ]
