# Generated by Django 2.2.2 on 2019-08-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0007_importcsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importcsv',
            old_name='profile_pic',
            new_name='csvfile',
        ),
    ]
