# Generated by Django 2.2.2 on 2019-08-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0008_auto_20190807_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_client',
            name='profile_pic',
            field=models.FileField(blank=True, default='clientdp/default.png', null=True, upload_to='clientdp'),
        ),
    ]
