# Generated by Django 2.2.2 on 2019-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0011_auto_20190807_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='language',
            new_name='projname',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='projpaytype',
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
        migrations.AddField(
            model_name='project',
            name='curr',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='maxprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='minprice',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='projfile',
            field=models.FileField(default=2, upload_to='projectfiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='projskills',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='projdesc',
            field=models.CharField(max_length=1000),
        ),
    ]
