# Generated by Django 2.2.2 on 2019-08-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0012_auto_20190808_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_client'),
            preserve_default=False,
        ),
    ]
