# Generated by Django 2.2.2 on 2019-09-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0013_project_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
