# Generated by Django 2.2.2 on 2019-09-27 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0015_auto_20190927_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_client',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
