# Generated by Django 2.2.2 on 2019-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0019_auto_20190927_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_developer',
            name='dob',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
