# Generated by Django 2.2.2 on 2019-10-10 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultra', '0020_auto_20190927_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfile', models.FileField(upload_to='finalproject')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_developer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Project')),
            ],
        ),
    ]
