# Generated by Django 2.2.2 on 2019-10-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Aid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='developerdp')),
            ],
        ),
        migrations.CreateModel(
            name='importcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(upload_to='importcsv')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('projname', models.CharField(max_length=50)),
                ('projdesc', models.CharField(max_length=1000)),
                ('projfile', models.FileField(upload_to='projectfiles')),
                ('projskills', models.CharField(max_length=100)),
                ('projpaytype', models.CharField(max_length=50)),
                ('curr', models.CharField(max_length=20)),
                ('minprice', models.IntegerField()),
                ('maxprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration_client',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(blank=True, default=0, null=True)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('addresh', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_pic', models.FileField(blank=True, default='clientdp/default.jpg', null=True, upload_to='clientdp')),
            ],
        ),
        migrations.CreateModel(
            name='Registration_developer',
            fields=[
                ('Did', models.AutoField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField(blank=True, default=0, null=True)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('addresh', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.IntegerField(blank=True, default=0, null=True)),
                ('skill', models.CharField(max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('profile_pic', models.FileField(blank=True, default='developerdp/default.jpg', null=True, upload_to='developerdp')),
            ],
        ),
        migrations.CreateModel(
            name='projectfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfile', models.FileField(upload_to='finalproject')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_developer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_client'),
        ),
        migrations.CreateModel(
            name='noti_developer',
            fields=[
                ('noti_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('recev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_developer')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Registration_developer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ultra.Project')),
            ],
        ),
    ]
